from Api.models.Region import Region
from Api.models.cliente import Cliente
from Api.models.cliente_plan_contrato import ClientePlanContrato
from Api.models.comuna import Comuna
from Api.models.corredora import Corredora
from Api.models.cuenta_acceso import CuentaAcceso
from Api.models.direccion import Direccion
from Api.models.estado_propiedad import EstadoPropiedad
from Api.models.factura import Factura
from Api.models.inmobiliaria import Inmobiliaria
from Api.models.linea_factura import LineaFactura
from Api.models.linea_orden_compra import LineaOrdenCompra
from Api.models.operacion import Operacion
from Api.models.orden_compra import OrdenCompra
from Api.models.particular import Particular
from Api.models.plan import Plan
from Api.models.propiedad import Propiedad
from Api.models.provincia import Provincia
from Api.models.proyecto import Proyecto
from Api.models.publicacion import Publicacion
from Api.models.telefono import Telefono
from Api.models.tipo_cliente import TipoCliente
from Api.models.tipo_operacion import TipoOperacion
from Api.models.tipo_propiedad import TipoPropiedad
